// <auto-generated />
namespace ProjectToDoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updated1404 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated1404));
        
        string IMigrationMetadata.Id
        {
            get { return "201409291304440_updated 1404"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
